# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Colombo Chetty Genealogy 
email: ben.anandappa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This website contains genealogical research of the Colombo Chetty people conducted by Ben Anandappa. 
baseurl: "/family-history" # the subpath of your site, e.g. /blog
url: "https://benafa.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-pdf-embed
  - jekyll-lunr-js-search

search: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  photos:
    output: true
  conversations: 
    output: true
  newspaper:
    output: true
    share: true
  vital:
    output: true 
  tree:
    output: true 
  marriage:
    output: true
    share: true



defaults:
  # _portfolio
  - scope:
      path: ""
      type: posts
    values:
      share: true
  - scope:
      path: ""
      type: newspaper
    values:
      share: true
  - scope:
      path: ""
      type: tree
    values:
      share: true
  - scope:
      path: ""
      type: marriage
    values:
      share: true

footer:
  links:
    - label: "About"
      url: "about"
    - label: "Account"
      url: "account"
    - label: "Disclaimers"
      url: "disclaimers"

# for posts
permalink: /:year/:month/:day/:title.html

logo: "/assets/images/emmanuel.jpg"

repository: "benafa/family-history"

og_image: "assets/images/emmanuel_header.png"

future: true

author:
  name: "Ben Anandappa"

# for orchestration
environment: "dev"

# for comments
comment-read: https://docs.google.com/spreadsheets/d/1C_2H4sYcH_D0UJNL_K7JXlLC8mzaT8lR9-a_OOGHFxY
comment-post: https://docs.google.com/forms/d/e/1FAIpQLScJBOhKrRYnXFlNH5VJ0iOxWALEV4BQxwpufT6Vqm6RfGOvhw
comment-post-fields: [ entry.1752653560, entry.1655801826, entry.2109089964, entry.1517318323]
